Update build_loop.yml

diff --git a/.github/workflows/build_loop.yml b/.github/workflows/build_loop.yml
--- a/.github/workflows/build_loop.yml
+++ b/.github/workflows/build_loop.yml
@@ -297,16 +297,16 @@ jobs:
 
           # the final customization listed above CANNOT have a continuation character
           # more customizations can be pasted after this line
-          
-          # Patch Fastlane Match to not print tables
-          - name: Patch Match Tables
-          run: |TABLE_PRINTER_PATH=$(ruby -e 'puts Gem::Specification.find_by_name("fastlane").gem_dir')/match/lib/match/table_printer.rb
-          if [ -f "$TABLE_PRINTER_PATH" ]; then
-          sed -i "" "/puts(Terminal::Table.new(params))/d" "$TABLE_PRINTER_PATH"
-          else
-          echo "table_printer.rb not found"
-          exit 1
-          fi
+      # Patch Fastlane Match to not print tables
+      - name: Patch Match Tables
+        run: | 
+         TABLE_PRINTER_PATH=$(ruby -e 'puts Gem::Specification.find_by_name("fastlane").gem_dir')/match/lib/match/table_printer.rb
+         if [ -f "$TABLE_PRINTER_PATH" ]; then
+         sed -i "" "/puts(Terminal::Table.new(params))/d" "$TABLE_PRINTER_PATH"
+         else
+         echo "table_printer.rb not found"
+         exit 1
+         fi
 
       # Install project dependencies
       - name: Install Project Dependencies
